### ISSUE TITLE
Using pdf format for output throws an error

### ISSUE THREAD

**Issue by zlotny** [limedocs/limedocs-wiki-converter#5]
Using version: `0.1.12`

Using lwc like this: `lwc -f pdf ./MySoftware.wiki`

Gives me this error:
```events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:999:13)
    at Pipe.onread (net.js:629:25)```

HTML works fine. Any suggestions? Thank you so much

**Comment by zlotny** [comment]
Nevermind, I solved that issue. I had not installed wkhtmltopdf.

Now I have another problem. Everytime I generate a PDF it is corrupt (tested with okular and Acrobat Reader 9 in Linux)
